# Generated by Django 4.2.29 on 2026-03-17 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': '智能警告记录', 'verbose_name_plural': '智能警告记录'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '物联网设备', 'verbose_name_plural': '物联网设备'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name': '农场配置', 'verbose_name_plural': '农场配置'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': '视觉采集记录', 'verbose_name_plural': '视觉采集记录'},
        ),
        migrations.AddField(
            model_name='alert',
            name='algorithm_version',
            field=models.CharField(blank=True, help_text='触发该警告所使用的视觉AI模型或规则引擎版本。', max_length=64, verbose_name='算法版本号'),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence',
            field=models.FloatField(blank=True, help_text='视觉识别结果的置信度分值，范围通常在 0~1 之间。', null=True, verbose_name='模型置信度'),
        ),
        migrations.AddField(
            model_name='alert',
            name='recognition_box',
            field=models.CharField(blank=True, help_text='以字符串形式存储的检测框坐标，例如 [x1, y1, x2, y2]。', max_length=128, verbose_name='检测框坐标'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(help_text='警告在平台侧被记录的时间。', verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='发起该警告的操作账号，算法自动触发时可为空。', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='触发用户'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, help_text='触发该警告的具体设备，部分规则可能只关联农场不关联设备。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.device', verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='farm',
            field=models.ForeignKey(help_text='产生该警告的农场或温室。', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.farm', verbose_name='所属农场'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='指示该警告是否已经由值班人员完成闭环处理。', verbose_name='是否已处置'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(blank=True, help_text='对警告产生原因、建议处置措施等进行详细说明。', verbose_name='警告详情'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], help_text='区分低、中、高不同严重程度，便于分级响应。', max_length=10, verbose_name='警告级别'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(help_text='用于在列表中快速识别问题类型的简短标题。', max_length=100, verbose_name='警告标题'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('camera', '固定摄像头'), ('sensor', '环境传感器')], help_text='区分固定摄像头、环境传感器等不同类型。', max_length=20, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='farm',
            field=models.ForeignKey(help_text='设备安装所在的农场或温室。', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoring.farm', verbose_name='所属农场'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_online_time',
            field=models.DateTimeField(help_text='设备最近一次成功与平台通讯的时间，用于判断在线状态。', verbose_name='最近在线时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text='设备在农场中的具体安装位置信息。', max_length=200, verbose_name='安装位置'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='边缘侧摄像头或传感器的业务名称。', max_length=100, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='在线', help_text='设备当前的连通状态，如在线、离线、维护中等。', max_length=20, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, help_text='对农场的作物类型、种植模式等进行补充说明。', verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(blank=True, help_text='农场所在的省市区、地块或温室编号等位置信息。', max_length=200, verbose_name='地理位置'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(help_text='农场或示范园区的名称，用于在平台中唯一标识生产单元。', max_length=100, verbose_name='农场名称'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='capture_time',
            field=models.DateTimeField(help_text='图像在边缘侧实际采集的时间，用于时序分析。', verbose_name='采集时间'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.CharField(blank=True, help_text='对该次采集场景的补充说明，例如作物品种、拍摄角度等。', max_length=255, verbose_name='业务描述'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='device',
            field=models.ForeignKey(help_text='产生该次图像采集的摄像头设备。', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='monitoring.device', verbose_name='采集设备'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='image_path',
            field=models.CharField(blank=True, help_text='存储于静态目录或对象存储中的图像访问路径。', max_length=255, verbose_name='图像路径'),
        ),
    ]
