# Generated by Django 4.2.29 on 2026-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_alert_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='algorithm_version',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='recognition_box',
        ),
        migrations.AlterField(
            model_name='alert',
            name='confidence',
            field=models.FloatField(blank=True, help_text='对本次警告依据的识别或判断结果进行 0~1 量化评分。', null=True, verbose_name='识别可靠性评分'),
        ),
    ]
