# Generated by Django 4.2.29 on 2026-03-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_alert_algorithm_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='extra_info',
            field=models.TextField(blank=True, help_text='用于记录设备的特殊功能描述，如变焦倍率、轨道参数等', null=True, verbose_name='设备备注/扩展信息'),
        ),
    ]
